[package]
name = "packadder"
version = "0.1.0"
edition = "2024"

[dependencies]
struct_pack_macro = { path = "struct_pack_macro" }
byteorder = "1.5"

[dev-dependencies]
anyhow = "1.0.101"
pyo3 = { version = "0.22", features = ["auto-initialize"] }