[package]
name = "struct_pack_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
byteorder = "1.5.0"
nom = "8.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
